### ISSUE TITLE
$10 in bash does not get colorized correctly

### ISSUE THREAD

**Issue by aeschli** [atom/language-shellscript#102]
_From @Tyriar on February 2, 2018 19:43_

<img width="265" alt="screen shot 2018-02-02 at 11 42 22 am" src="https://user-images.githubusercontent.com/2193314/35751683-39c13cdc-080e-11e8-9d5f-f752bf657da7.png">

```sh
echo '10:'$9
echo '10:'$10
```

_Copied from original issue: Microsoft/vscode#42845_

**Comment by 50Wliu** [comment]
GNU's Bash Reference Manual [states](https://www.gnu.org/software/bash/manual/html_node/Positional-Parameters.html) "When a positional parameter consisting of more than a single digit is expanded, it must be enclosed in braces".

Am I missing something here?

**Comment by Tyriar** [comment]
@50Wliu I guess that's fine then according to spec, `$10` does actually expand correctly though. Feel free to close.

**Comment by 50Wliu** [comment]
:+1: Closing.
