### ISSUE TITLE
Escaped double quote in here string breaks highlighting

### ISSUE THREAD

**Issue by kretep** [atom/language-shellscript#110]
I expect the following to be properly highlighted, but it is not:
```bash
echo $(bc <<< "$(cat file.txt | sed 's/"//g')")
echo "This is not highlighted properly"
```

**Comment by bengtbrodersen0042** [comment]
For me it works wit the latest version

**Comment by rsese** [comment]
Thanks @bengtbrodersen0042 :+1: This looks ok to me too with 1.40.0-nightly15 on macOS 10.12.6.  With the cursor in the string on line 2:

![shell-string](https://user-images.githubusercontent.com/734194/60287899-a4fe5500-98d8-11e9-8429-32cc41324793.png)

Going to go ahead and close this out, but if I'm misunderstanding anything please let me know.
