### ISSUE TITLE
Shell script grammar identified as "Bash" instead of "Shell Script" when experimental Tree Sitter Parsing is enabled

### ISSUE THREAD

**Issue by slackmate** [atom/language-shellscript#113]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When the experimental Tree Sitter Parsers are enabled in Atom the grammar of a vanilla shell script is identified as "Bash" instead of "Shell Script". This works as expected when the Tree Sitter Parsers are disabled. It breaks the package `rgbkrk/atom-script` which fails to run a given script with an error "Command not configured for Bash!" as it expects the grammar to be "Shell Script".

### Steps to Reproduce

1. Enable Tree Sitter Parsers
2. Open any shell script

**Expected behavior:** Grammar of the shell script should be set to "Shell Script"

**Actual behavior:** Grammar is set to "Bash"

**Reproduces how often:** 100%

### Versions

macOS 10.11.6

`atom --version`
Atom: 1.26.1
Electron: 1.7.11
Chrome: 58.0.3029.110
Node: 7.9.0

**Comment by 50Wliu** [comment]
Due to https://github.com/atom/language-shellscript/blob/b0f15084c138256becea931f63f0562c44c515cb/grammars/tree-sitter-bash.cson#L2.  @maxbrunsfeld is there a reason everything is referred to as 'Bash'?

**Comment by maxbrunsfeld** [comment]
I put it back to "Shell Script" in https://github.com/atom/language-shellscript/commit/2fb9344e6cbf4067d85ad7eabc3f00a88d7521cf.

**Comment by slackmate** [comment]
Thank you @maxbrunsfeld for fixing this 👍
