### ISSUE TITLE
.cfg files for segmenting .sh (bash) scripts not recognized/listed

### ISSUE THREAD

**Issue by ninjamonkey198206** [atom/language-shellscript#116]
I use .cfg files and include them in a very large bash script, but they're used quite frequently. I don't know if they actually have to use that extension, but that's what all of my searching came up with as the standard. It's very handy for segmenting scripts or making a collection of smaller scripts into one.

I thought it might be useful to either add that as an optional supported file type, with the same highlighting as .sh files, or to add an option to allow users to add file types and select which currently supported file type highlighting to use for them.

**Comment by 50Wliu** [comment]
Please see https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539 for how to do the latter.

**Comment by ninjamonkey198206** [comment]
I just read the FAQ you linked, and it assumes that the reader already understands the ins and outs of Atom.

I literally installed it less than two weeks ago, and I've used it twice.

After digging around, I think I may have an idea of what was vaguely described (imo, it was a poor example of, well, an example, as it didn't give references to indicate which parts of the code snippet were what, such as comments), so to anyone new to writing code of any kind, it's not exactly easy to understand. I've been doing this for four years in my free time and I still consider myself at an amateur level.

If you could take a second and help clear it up for me, I'd greatly appreciate it. If not, thanks for the original link, and I'll try my Google-fu with that link for inspiration.

**Comment by 50Wliu** [comment]
Yeah, so you'll want to open up your Atom config file (`Application: Open Your Config` from the Command Palette).

Then, under the `core` section (create one if it doesn't already exist), add the following:
```coffee
customFileTypes:
  'source.shell': [
    'cfg'
  ]
```

Please tell me if that doesn't work.

**Comment by ninjamonkey198206** [comment]
I'll try it as soon as I get to my laptop.

I think you've cleared it up a bit for me, so:

In the reference to source.shell, .shell is the launguage type, and that should be referenced in the packages section, in the built-in or added package that contains the language type. That source.xx is what sets the language type in the code you provided, and the entry (cfg in this case) is the additional file type to be recognized as part of that language type.

Does that sound right, or good enough for government work?

**Comment by 50Wliu** [comment]
Yes, that's mostly correct.  You can get the `source.shell` part by looking at the first item that appears when you execute `Editor: Log Cursor Scope`.
