### ISSUE TITLE
Wrapped stdin highlighted improperly.

### ISSUE THREAD

**Issue by envygeeks** [atom/language-shellscript#119]
### Description

Wrapped stdin is highlighted improperly.

### Steps to Reproduce

1. Wrap
2. Stdin

**Expected behavior:** [What you expect to happen]

Proper highlighting

**Actual behavior:** [What actually happens]

Wrong highlighting

### Additional Information

```bash
pkg::as_single_line_list() {
  (sed "s/^ *//; s/ *\$//; /^\$/d" \
   | tr "\n" " ") < /dev/stdin
}
```

<img width="326" alt="image" src="https://user-images.githubusercontent.com/99763/44063268-871b6cec-9f25-11e8-856f-5b4c60cb58c8.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/99763/44063322-9a6333de-9f25-11e8-9ace-08c1c965886d.png">

**Comment by 50Wliu** [comment]
Fixed in tree-sitter.
