### ISSUE TITLE
`if` keyword in bash source leaks highlighting outside code block

### ISSUE THREAD

**Issue by chaitanyathengdi** [atom/language-shellscript#120]
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
Couldn't use safe mode: packages were showing as not installed
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
Found these, but they don't seem to be duplicates: 
https://github.com/atom/language-shellscript/issues/22
https://github.com/atom/language-shellscript/issues/21
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages
Not my package that's using it, so  can't say: https://github.com/asciidoctor/atom-language-asciidoc/
### Description

I was writing code snippets in an AsciiDoc document(which uses this package) using the bash syntax highlighter, and I noticed that the highlighting was leaking outside the [source,bash] block. This is evident after the "let's" in the bottom of the screenshot below:

![leaking highlighting](https://user-images.githubusercontent.com/14993220/44089053-0a786adc-9fe3-11e8-8660-5149b0582daf.png)

### Steps to Reproduce
Just write some code containing a lone if statement inside a source block.

**Expected behavior:** Syntax highlighting works as it should.

**Actual behavior:** Syntax highlighting bleeds outside the source block.

**Reproduces how often:** Every time it is used.

### Versions
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

#### Syntax example

```adoc
[source,bash]
----
~/poems/The Road Not Taken$ git checkout my_first_poem
Switched to branch 'my_first_poem'
~/poems/The Road Not Taken$ cat >> poem.txt
Oh, I kept the first for another day!
Yet knowing how way leads on to way,
I doubted if I should ever come back.
~/poems/The Road Not Taken$ git add poem.txt
~/poems/The Road Not Taken$ git commit -m "A Road Not Taken: Add the third verse, second part"
[my_first_poem d68c1b5] A Road Not Taken: Add the third verse, second part
 1 file changed, 3 insertions(+)
~/poems/The Road Not Taken$
----

Okay. Now Let's bring both the changes together.
```
If I remove the "if" in the poem above or replace it with something else, the problem goes away:

![screenshot from 2018-08-14 16-59-25](https://user-images.githubusercontent.com/14993220/44089191-7dfbeb0a-9fe3-11e8-8e5f-30beddf71efe.png)

This is problematic. I can't just remove that "if" because I need it to be there, and in any case this shouldn't happen.

Issue reference in Asciidoc's package: https://github.com/asciidoctor/atom-language-asciidoc/issues/191

**Comment by 50Wliu** [comment]
What you're showing is not bash but rather a shell session. You should ask asciidoctor to support the [shell-session](https://github.com/atom/language-shellscript/blob/cdcdd8d86c03a8e433d3f191d7efdf37a249f187/grammars/shell-session.cson) grammar instead.
