### ISSUE TITLE
Shell Script Language Mode: "endif" not highlighted correctly on tcsh scripts

### ISSUE THREAD

**Issue by aeschli** [atom/language-shellscript#123]
_From @dsanz006 on July 24, 2018 9:2_

I am writing a very simple tcsh script on VS code and I can see that the shellscript language mode doesn't highlight the syntax correctly in all cases. For example, on an if/else instruction like this one:

`if (${ERRORCODE} != 0) then`
    `echo "Error"`
`else`
    `echo "Success"`
`endif`

Here, `if`, `then` and `else` are highlighted correctly, but `endif` is not. It should be highlighted as the rest.

I don't know if this happens with more keywords, because I have used VS code for tcsh scripts in a very limited way.

- VSCode Version: 1.25.1
- OS Version: Ubuntu 16.04.4 LTS

_Copied from original issue: Microsoft/vscode#54926_

**Comment by aeschli** [comment]
I see the same in Atom:
![image](https://user-images.githubusercontent.com/6461412/45538304-00a69880-b807-11e8-8e21-802c9b1a02a2.png)

**Comment by 50Wliu** [comment]
We primarily support sh/bash, and this tcsh script doesn't look like it's compliant with bash's syntax. I'll ask the team what we want to do with this.
