### ISSUE TITLE
Heredoc syntax incorrect

### ISSUE THREAD

**Issue by mcandre** [atom/language-shellscript#134]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

language-shellscript incorrectly highlights heredocs with inline shell command execution.

*Edit by @rsese to add screenshots*

With Tree-sitter disabled:

![shell-syntax](https://github-slack.s3.amazonaws.com/monosnap/Settings__worktest-tree-sitter_2018-12-27_15-45-53.png)

With Tree-sitter:

![string](https://github-slack.s3.amazonaws.com/monosnap/test.sh__worktest-tree-sitter_2018-12-27_15-48-05.png)

### Steps to Reproduce

1. Write:

```sh
cat <<EOF | apt-key add -
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.6
Comment: Hostname: pgp.mit.edu

mQINBFXxKzoBEADIsc23k+Z3gegyjddHXZvUc9Hi8PBPiRSoriFJ4HI21MWgNS4jEz5zosIz
...
=uoNF
-----END PGP PUBLIC KEY BLOCK-----
EOF
```

**Expected behavior:** [What you expect to happen]

language-shellscript recognizes that the `| apt-key add -` piece is not part of the heredoc content, but rather an shell expression around the heredoc.

**Actual behavior:** [What actually happens]

language-shellscript highlights `| apt-key add -` as a string, as if it were part of the heredoc.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

0.27.9

**Comment by rsese** [comment]
Thanks @mcandre - reproduced with 1.33.1 on macOS 10.12.6.  With Tree-sitter disabled:

![shell-syntax](https://github-slack.s3.amazonaws.com/monosnap/Settings__worktest-tree-sitter_2018-12-27_15-45-53.png)

With Tree-sitter:

![string](https://github-slack.s3.amazonaws.com/monosnap/test.sh__worktest-tree-sitter_2018-12-27_15-48-05.png)

**Comment by maxbrunsfeld** [comment]
Just to clarify, I think this was *not* a regression. The older TextMate grammar also incorrectly highlighted the command after the pipe (`apt-key add -`) as part of the heredoc.

I just fixed this in the Tree-sitter parser, so in new builds of Atom, if you have Tree-sitter enabled, you won't see this problem.
