### ISSUE TITLE
Syntax highlighting broken for Base n notation for arithmetic evaluation

### ISSUE THREAD

**Issue by softwarecreations** [atom/language-shellscript#145]
`Atom 1.38.2 x64`
`language-shellscript 0.27.11`

Example bash code where syntax highlighting is broken
```
#!/bin/bash
((10#$weekday < 6 && 10#$hour > 4 && 10#$hour < 18 )) && uploadSpeed=5 || uploadSpeed=30
```
![image](https://user-images.githubusercontent.com/28704571/60017180-6ffbc380-9688-11e9-8984-7f514b36a4fc.png)

Documentation for Base n notation in the bash manual under ARITHMETIC EVALUATION (Line 1534) and more specifically at line 1573

Quote from the manual

> Constants with a leading 0 are interpreted as octal numbers. A leading 0x or 0X denotes hexadecimal. Otherwise, numbers take the form [base#]n, where the optional base is a decimal number between 2 and 64 representing the arithmetic base, and n is a number in that base. If base# is omitted, then base 10 is used. When specifying n, the digits greater than 9 are represented by the lowercase letters, the uppercase letters, @, and _, in that order. If base is less than or equal to 36, lowercase and uppercase letters may be used interchangeably to represent numbers between 10 and 35.

**Comment by Ben3eeE** [comment]
Thanks for taking the time to contribute!

This is actually an issue in tree-sitter /cc: https://github.com/tree-sitter/tree-sitter-bash/issues/41. You may want to subscribe there for updates.

**Comment by softwarecreations** [comment]
> Thanks for taking the time to contribute!
> 
> This is actually an issue in tree-sitter /cc: [tree-sitter/tree-sitter-bash#41](https://github.com/tree-sitter/tree-sitter-bash/issues/41). You may want to subscribe there for updates.

Thanks, I've subbed that issue.
