### ISSUE TITLE
Nested parameter expansions break syntax highlighting

### ISSUE THREAD

**Issue by teki** [atom/language-shellscript#19]
Example:
```sh
#!/bin/bash

# this is broken already
A=${B:-${C}}
# but this makes it worse
A=${B:-"${C}"}

K=2
```

**Comment by 50Wliu** [comment]
Can you please explain what exactly is broken (preferably through an image of Atom), and also include what Atom version you're using and whether or not it can be reproduced in safe mode (`atom --safe`)?  Thanks.

**Comment by teki** [comment]
> Can you please explain what exactly is broken (preferably through an image of Atom), 

![screen shot 2015-09-15 at 12 53 56 pm](https://cloud.githubusercontent.com/assets/5516/9866699/ed62bfd2-5ba8-11e5-8e13-bf7ecd2f7023.png)

In the first example it the second closing bracket is not red.

The second example is similar, but the first double-quote was implicitly closed by the first matching closing bracket, so the second double-quote is interpreted as a start of string.

> and also include what Atom version you're using 

1.0.11

> and whether or not it can be reproduced in safe mode (atom --safe)? 

Yes.

Sorry for leaving out details.

**Comment by 50Wliu** [comment]
The quotes appear to be highlighted for me now but the first nested expansion is still broken.  @teki can you confirm (on Atom 1.0.19)?

**Comment by teki** [comment]
I can confirm. It is a lot better, but the first one is still broken, the opening bracket before C is red.

**Comment by 50Wliu** [comment]
@teki This should be fixed in the next version of Atom.
