### ISSUE TITLE
Syntax Highlighting getting confused around too many quotes

### ISSUE THREAD

**Issue by faveja** [atom/language-shellscript#29]
Hello,

Syntax highlighting seems to be getting confused around too many quotes. From line 136 on, in the screen shot of ATOM, highlighting seems incorrect. The if in ifconfig, on line 136, should not be blue. ipAddr, on line 137, should not be green. Everything after line 137 is green.

![screen shot of ATOM](https://cloud.githubusercontent.com/assets/8634264/10580308/c69f3904-7631-11e5-9d32-7b3df291bfed.png)

The code is running without any issues when run in bash, and is correctly highlighted by other programs, for example VIM shipped with OS X.

![screen shot of VIM](https://cloud.githubusercontent.com/assets/8634264/10580532/bba14302-7632-11e5-8bd5-b97e0d93e865.png)

-Florin

**Comment by izuzak** [comment]
Thanks for the report, @faveja. Can you share the text from those screenshots here? Also, it's always helpful if you mention your OS+version and Atom version, and if you can reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode). You can find some guidelines for submitting issues [here](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by 50Wliu** [comment]
I'm going to hazard a guess and say that I fixed this in atom/language-shellscript#23 and atom/language-shellscript#26.

@faveja in addition to what @izuzak recommended, can you also try updating to Atom 1.1.0-beta1 and see if your issue still exists?

**Comment by izuzak** [comment]
Thanks, @50Wliu :bow: Just going to drop a link to Atom beta for easy downloading: 

https://github.com/atom/atom/releases/tag/v1.1.0-beta1

**Comment by faveja** [comment]
@50Wliu I have tested v1.1.0-beta1 and the issue is RESOLVED.

@izuzak, in case you still want this information.
OS: Apple OS X 10.11
ATOM: 1.0.19

```
macUDID="$(ioreg -d 2 -c IOPlatformExpertDevice | sed -n 's/.*IOPlatformUUID.*"\(.*\)"/\1/p')"
macMac="$(ifconfig en0 ether | sed -n 's/.*ether \(.*\) /\1/pg' | sed 's/://g')"
ipAddr="$(ipconfig getifaddr ${ethernetPort})"

# Variable that stops computer name check loop
computerNameVerification="0"
```

Thank you!
-Florin

**Comment by 50Wliu** [comment]
Great to hear :smile:!
