### ISSUE TITLE
Resources for modifications?

### ISSUE THREAD

**Issue by edge226** [atom/language-shellscript#46]
Hello. Let me start of by saying I tried the plugin out and it works great.

I have some issues that are going to be specific to my coding style so I think I would like to fork the repo and make modifications, Pushing changes that I feel are general to bash back into the project and keeping the ones that clearly are meant for the coding style of my project where it belongs.

Eg. Every time I create a function I append to two arrays, one contains the variables used in the function and the other contains the function name. This data is used within a cleanup function at the end of the scripts.

It would be really nice to have extra options to handle this functionality sort of functionality and make more advanced bash scripting more accessible.

There are a few different types of if statements, for statements, while loops that are not within this framework currently. Mainly the ability to select the type of brackets you may want to use. In bash you do not always want to use if [[ "$this" = "that" ]] style, You may need to use if (( "$number" >= "$Limit" )) for arithmatic.

Examples of a different while statement is when you read data from a file using a [while loop](http://mywiki.wooledge.org/DontReadLinesWithFor).

I see from other issues that you want spec files for changes made to the sources. Do you have any resources on what needs to be done for the spec file modification or other helpful resources that will help me with figuring out parts of the source code I do not understand?

**Comment by 50Wliu** [comment]
> I see from other issues that you want spec files for changes made to the sources.

If you just want to change some of the snippets, no specs are needed.

**Comment by edge226** [comment]
Great. Thanks for the reply :+1:
