### ISSUE TITLE
How do you test changes?

### ISSUE THREAD

**Issue by edge226** [atom/language-shellscript#47]
So I forked this, Tried to create a new apm under language-orbos-style-shellscripts, First publish failed because it wanted a tag. No idea what I did wrong at all...

Second attempt at fixing the command and pushing results in:
```
$ apm publish language-orbos-style-shellscript
Registering language-orbos-style-shellscript ✓
Preparing and tagging a new version ✗                                        
npm ERR! npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease]                                                 
npm ERR! (run in package dir)                                                
npm ERR! 'npm -v' or 'npm --version' to print npm version (2.13.3)           
npm ERR! 'npm view <pkg> version' to view a package's published version      
npm ERR! 'npm ls' to inspect current package/dependency versions
```

Every subsequent run gives me: 
```
Registering language-orbos-style-shellscript ✗
Registering package in orbos/language-orbos-style-shellscript repository failed: A package by that name already exists
```

So how do I actually test changes to make sure they perform as desired before doing pushes? This seems like a really counter-intuitive way to do things to me, I do not and will never push "I think this should work." code without being able to test it and thats how this system appears to me...

Is the repo basically a burner now since if someone uses a repo name you cant use it again?

**Comment by lee-dohm** [comment]
There is a full tutorial on how to develop packages in the [Atom Flight Manual](http://flight-manual.atom.io) here:

http://flight-manual.atom.io/hacking-atom/sections/package-word-count/

including how to run tests. For working on a package that you have forked and cloned, you can run the `apm link --dev` command to set up the package for running when Atom is launched in Dev Mode with `atom --dev`.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For questions about how to develop and maintain packages, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
