### ISSUE TITLE
Add extension 

### ISSUE THREAD

**Issue by TheChymera** [atom/language-shellscript#48]
I am developing package atoms for Gentoo - these `.ebuild` files are little more than lists of shell variables, and I would like to benefit from the according highlighting in atom. How do I add `.ebuild` to the list of suffixes which will load the syntax from this package?

**Comment by 50Wliu** [comment]
@TheChymera You can add it in [this list](https://github.com/atom/language-shellscript/blob/master/grammars/shell-unix-bash.cson#L3).
