### ISSUE TITLE
if statement detection fail

### ISSUE THREAD

**Issue by Noltari** [atom/language-shellscript#5]
First of all, as requested on the guidelines (I guess this happens on every Atom version/OS):
Atom v0.165.0
Windows 8.1 x64

As you can see in the images below, there's a bug which causes Shellscript language to go mad if there's an if/while/for... statement inside a command:
![atom_bash_if_fail_1](https://cloud.githubusercontent.com/assets/264346/5598636/395a4eb8-92ba-11e4-8ce4-034d4ee54df5.png)
Now we change dd if to in:
![atom_bash_if_fail_2](https://cloud.githubusercontent.com/assets/264346/5598641/41954aec-92ba-11e4-8226-f42ff786a3f0.png)

Regards,
Álvaro.

**Comment by FunTimeCoding** [comment]
+1 I also came across this and reported it here: https://discuss.atom.io/t/markdown-syntax-highlight-bug/14502

**Comment by Noltari** [comment]
Bump
