### ISSUE TITLE
Quotes in comments surrounded by backticks not highlighted correctly

### ISSUE THREAD

**Issue by Ajedi32** [atom/language-shellscript#54]
As a hack for adding inline comments to a multi-line bash command, I decided to use comments nested inside bash substitution backticks, as suggested by [this StackOverflow answer](http://stackoverflow.com/a/12797512/1157054).

While this works fine in bash, Atom's syntax highlighting doesn't handle it correctly:

```sh
curl                              \
  `# Fail on http errors`         \
  --fail                          \
  `# Don't show progress`         \
  --silent                        \
  `# ...but still show errors`    \
  --show-error                    \
  `# Follow redirects`            \
  --location                      \
  `# Add to authorized keys`      \
  --output ~/.ssh/authorized_keys \
  `# Fetch key from GitHub`       \
  https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
```

Renders as:

![Single quote in comment renders as multiline string](https://cloud.githubusercontent.com/assets/1876931/17858427/4c59ff28-684b-11e6-843c-419ff20e0afe.png)

As you can see, the single quote in the word "Don't" is being parsed as the start of a multi-line string, even though the quote is part of a comment.

**Comment by Herst** [comment]
More such examples from https://github.com/github/linguist/issues/3186:

```sh
printf '(%s)' foo "`# '`" bar
```
```sh
printf '(%s)' foo "`# "`" bar
```
```sh
printf '(%s)' foo "`# '`" \
  bar
```
```sh
printf '(%s)' foo "`# "`" \
  bar
```
