### ISSUE TITLE
.profile is not being recognized as a shellscript file

### ISSUE THREAD

**Issue by cbcoutinho** [atom/language-shellscript#69]
My `.bashrc` file is correctly recognized as a shell script, but my `.profile` file is not - no syntax highlighting or filename recognition whatsoever.

I looked at [shell-unix-bash.cson, lines 3-26](https://github.com/atom/language-shellscript/blob/master/grammars/shell-unix-bash.cson#L3-L26) and see that `.profile` is a supported filetype along with `.bashrc`, so I'm not sure what the issue is. A missing period somewhere in a parser maybe? Anyways, I hope you have an easier time finding the problem that I am.

Thanks in advance!

**Comment by 50Wliu** [comment]
Just tried it out - it's getting recognized as PHP instead 😞.  Can you verify this @cbcoutinho?
https://github.com/atom/language-php/blob/master/grammars/php.cson#L16

**Comment by cbcoutinho** [comment]
Hi @Wliu - yes I just noticed now that you mentioned it, it is indeed being
caught up in PHP syntax.

**Comment by cbcoutinho** [comment]
And what's worse - I'm not even getting a PHP icon. If PHP is in fact correct about the file extension, then they have a file-icon issue on their hands as well.

What does atom allow you to do when two languages have identical file extensions?

Another one that comes to mind is Matlab `.m` files and Objective-C `.m` files. I just know I'm working with Matlab, but the grammar and syntax think otherwise

**Comment by 50Wliu** [comment]
You can set custom filetype associations: https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539

For MATLAB, try searching for a language package for it.  Community packages have higher precedence than core packages.

**Comment by cbcoutinho** [comment]
Wonderful, thanks for the link. I was able to fix the issue by overriding the file associations as described in your link.

Specifically, I solve the issue by adding the following snippet to my `config.cson`:

```
core:
  customFileTypes:
    'source.shell': ['profile']
    'source.matlab': ['m']
```

Thanks again for the quick reply!
