### ISSUE TITLE
Empty parentheses in a string causes the rest of the script to be rendered as a string

### ISSUE THREAD

**Issue by etiennemabille** [atom/language-shellscript#70]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Empty parentheses in a string causes the rest of the script to be rendered as a string

### Steps to Reproduce
Write the following text in a file and use "Shell Script" grammar.
```sh
#!/bin/bash
log() {
	local l_arg_message="$1"
	if [ -n "${l_arg_message}" ]; then
		echo "${FUNCNAME[1]}(): ${l_arg_message}"
	fi	
	echo "Hello World"
}
```

**Expected behavior:**
I expect atom to render the last 3 lines as code like this:
![2017-03-21 11_52_23-kubuntu_dev original en fonction - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/11175343/24144292/f4f430e0-0e2c-11e7-8e0a-112e37979391.png)

**Actual behavior:**
The last 3 lines are rendered as a string: 
![2017-03-21 11_53_48-kubuntu_dev original en fonction - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/11175343/24144354/31d66398-0e2d-11e7-97f3-a81bae98fabf.png)

**Reproduces how often:**
Other tests:
![2017-03-21 12_00_02-kubuntu_dev original en fonction - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/11175343/24144554/fae8fc14-0e2d-11e7-9caf-9fcf7af36931.png)

### Versions

```
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 ia32
python 2.7.6
git 1.9.1
```

**Comment by revolter** [comment]
I think I found the same problem as described [here][1].

  [1]: https://github.com/github/linguist/issues/3538

**Comment by qoomon** [comment]
I can confirm this problem.
Example to reproduce
```
echo "()"
a=1
```
`a=1` is highlighted as a string
