### ISSUE TITLE
wrong syntax high lighting

### ISSUE THREAD

**Issue by toralf** [atom/language-shellscript#73]
linguist blames this project :

https://github.com/github/linguist/issues/3581#issuecomment-297588036

**Comment by 50Wliu** [comment]
The examples you gave seem identical?

**Comment by toralf** [comment]
This commit 
https://github.com/toralf/tinderbox/commit/8949694523dca46029dc0b644609eef63a58e567
fixes it.

This looks fine
https://github.com/toralf/tinderbox/blob/8949694523dca46029dc0b644609eef63a58e567/bin/job.sh
whereas this
https://github.com/toralf/tinderbox/blob/b46685b8b58c8ffd29ec9172bddf50cfc30e5736/bin/job.sh
looks ugly between lines 458 and 581
