### ISSUE TITLE
Wrong syntax highlighting after certain combination of characters

### ISSUE THREAD

**Issue by SirUli** [atom/language-shellscript#75]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax highlighting breaks when using combination below

### Steps to Reproduce

Real World example:
```
func_get_current_user_host() {
  echo "$(who am i|awk '{print $(NF)}'|awk -F '[()]' '{print $2}')"
}
func_get_current_user_host
```
everything after the "echo" line will be with wrong syntax highlighting.

I've distilled it down to this: 
```
#!/bin/bash
echo "$(test '[()]')"
# From here on the syntax highlighting shows nonsense
echo "Here comes the end ;)"
```

**Expected behavior:**
Should be proper syntax highlighting also in the subsequent lines

**Actual behavior:**
Shows as if the "echo" never ended. Looks like it stumbles across the `'[` within a `"`

**Reproduces how often:**
100% of the cases

### Versions
OS: Windows 7

language-shellscript: 0.25.0

atom --version
```
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

apm --version
```
apm  1.17.0
npm  3.10.5
node 6.9.5 ia32
python 2.7.11
git 2.12.2.windows.2
visual studio
```

### Additional Information
![highlight](https://user-images.githubusercontent.com/151354/27176522-6cced2a8-51f5-11e7-88b6-bc0e3fa9e00a.jpg)

**Comment by rsese** [comment]
Is the empty parenthesis the issue /cc https://github.com/atom/language-shellscript/issues/70?

**Comment by 50Wliu** [comment]
Certainly looks like it.  Closing as a duplicate but please comment here if you disagree @SirUli.

**Comment by SirUli** [comment]
Indeed seems to be the same issue. Sorry didn't see that.

@50Wliu if i change the code from:
`echo "$(test '[()]')"`

to
`echo "$(test ' [()]')"`
(basically add one space in front of the parenthesis) then the highlighting works properly again. Not sure if that helps in any way.

Thanks for your time and dedication to this!
