### ISSUE TITLE
fails to parse string with parentheses "()"

### ISSUE THREAD

**Issue by jtmoon79** [atom/language-shellscript#81]
The following shell script does not terminate the string token on line 2.

     #!/bin/bash
     echo "()"
     echo bar

Line 3, `echo bar`, is errantly colored as a continuation of the string `"()"` on line 2.

----

Seen in [atom.io](https://github.com/atom/atom) version _1.17.2 x64_ using package _[language-shellscript](https://github.com/atom/language-shellscript) 0.25.0_.

This was reported in project [textmate/shellscript.tmbundle](https://github.com/textmate/shellscript.tmbundle) Issue [#43](https://github.com/textmate/shellscript.tmbundle/issues/43).

**Comment by 50Wliu** [comment]
I just fixed this in #79.  Should be out in Atom 1.21.0 when it's released.
