### ISSUE TITLE
Syntax highlighting broken after <<< is found in file contents

### ISSUE THREAD

**Issue by baziliolg** [atom/language-shellscript#82]
### Description

here-string <<< breaks Shell syntax highlighting

### Steps to Reproduce

Here's an example of code that makes my editor show the rest of the script in red:
```sh
if [[ -n ${COUNTRIES} && -z ${EXCLUDE_COUNTRIES} ]]; then
    IFS=', ' read -a countries_list <<< $COUNTRIES
    for i in ${countries_list[@]} ; do
        if ! grep $i ${_cm}; then
            logerror "Country code $i does not exist." && return ${C_ERROR}
        fi
    done
fi
```
Starting with line after the one with `<<<`, the rest of the file is shown in single red color. 
[Screenshot link](https://i.imgur.com/BPlmm9F.png)

**Expected behavior:** syntax highlighting should not get confused by <<<

**Actual behavior:** all the rest of the file contents are shown in single red color

**Reproduces how often:** every time here-string exists in Shell-script that I'm editing

### Versions
```
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1
```
OS is MacOS Sierra 10.12.6

**Comment by DanielRivasMD** [comment]
This issue came back after update 1.38

**Comment by 50Wliu** [comment]
@DanielRivasMD please open a new issue and we'll take a look!
