### ISSUE TITLE
Exponential loop in parsing?

### ISSUE THREAD

**Issue by Arcanemagus** [atom/language-shellscript#88]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

1. Type the following code in a document, mark it as `Shell Script`
    ```shell
    #!/bin/bash
    
    # ____________________________2
    ```

2. Add another `2` on the end

**Expected behavior:**

Memory usage to increase by a few bytes at most.

**Actual behavior:**

Memory usage increases by a few dozen gigabytes before Atom crashes 😱.

Note that this seems to be related to the number of `_` preceding the `2` on the line:
![image](https://user-images.githubusercontent.com/427137/32580139-ca8dbbd2-c498-11e7-98ce-7f8ac9f2d46a.png)

The first "bump" is at 23 `_`, the second is `24`, and the last is `25`.

**Reproduces how often:**

100% of the time.

### Versions

```
Atom    : 1.23.0-beta0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.10
npm  3.10.10
node 6.9.5 x64
atom 1.23.0-beta0
python 2.7.14
git 2.14.2.windows.3
visual studio 2015
```

OS: Windows 10 x64 Enterprise

### Additional Information

cc @50Wliu per request 😉.

**Comment by Arcanemagus** [comment]
As a note, this depends on the `_` character, replacing them with `-` allows Atom to work properly.

**Comment by 50Wliu** [comment]
This isn't caused by backtracking.  Interesting...
