### ISSUE TITLE
Failed to load a language-shellscript package grammar

### ISSUE THREAD

**Issue by fourthchakra** [atom/language-shellscript#95]
[Enter steps to reproduce:]

1. start up Atom 1.22 or 1.23
2. error immediately appears

Workaround is to edit .atom/packages/language-shellscript/grammars/tree-sitter-bash.cson, and add 
   'scopeName': 'text.tree-sitter'
as the first line. It appears this file requires updating.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [language-shellscript](https://github.com/atom/language-shellscript) package 0.26.0-0

### Stack Trace

Failed to load a language-shellscript package grammar

```
At Grammar missing required scopeName property: /Users/tdc/.atom/packages/language-shellscript/grammars/tree-sitter-bash.cson in /Users/tdc/.atom/packages/language-shellscript/grammars/tree-sitter-bash.cson

Error: Grammar missing required scopeName property: /Users/tdc/.atom/packages/language-shellscript/grammars/tree-sitter-bash.cson
    at /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:128:70
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:223:65
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
  at /packages/language-shellscript/grammars/tree-sitter-bash.cson:1:1
```

### Commands

```
     -0:44.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-mocha 0.0.12 
atom-ternjs 0.18.3 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
busy-signal 1.4.3 
docblockr 0.13.4 
file-icons 2.1.14 
git-control 0.9.0 
git-projects 1.17.0 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-flow 5.6.1 
linter-ui-default 1.6.10 
mocha 0.0.7 
nuclide 0.270.0 
open-recent 5.0.0 
react 0.17.0 
sort-lines 0.18.0 
tool-bar 1.1.0 
```

**Comment by 50Wliu** [comment]
@fourthchakra You aren't supposed to manually install language-shellscript.  Uninstalling it will force Atom to use its built-in version which should fix this issue.

**Comment by fourthchakra** [comment]
Uninstalling the package resolved the problem, thank you.

**Comment by senica** [comment]
For anyone running across this.... you cannot uninstall from the GUI. You'll have to uninstall using `apm uninstall langauge-shellscript` and then restart atom.

**Comment by whittede** [comment]
Sorry to necro-post a little bit, but Atom is detecting this Issue thread as the same one I'm encountering. 
I opened up Atom and my antivirus detected C:\Users\myUser\AppData\Local\atom\app-1.32.2\resources\app.asar.unpacked\node_modules\tree-sitter-bash\build\ **Release\tree_sitter_bash_binding.node** as a Trojan, and appears to have deleted the entire **Release** folder. This is on a Windows machine.

When I run the `apm uninstall language-shellscript` command, I receive the error _Failed to delete langauge-shellscript: Does not exist_ and the original Issue still appears even when I restart Atom (it does not appear to be re-installing the default `language-shellscript` package).

Should I just re-download the specific files that go in that **Release** folder (and if so, where can I get them?). And if I do, should I add the `'scopeName': 'text.tree-sitter'` line to the `tree-sitter-bash.cson`, as suggested in the original answer? Or is there a way to force Atom to install the `language-shellscript` package?

**Comment by rbergeron81** [comment]
> Sorry to necro-post a little bit, but Atom is detecting this Issue thread as the same one I'm encountering.
> I opened up Atom and my antivirus detected C:\Users\myUser\AppData\Local\atom\app-1.32.2\resources\app.asar.unpacked\node_modules\tree-sitter-bash\build\ **Release\tree_sitter_bash_binding.node** as a Trojan, and appears to have deleted the entire **Release** folder. This is on a Windows machine.
> 
> When I run the `apm uninstall language-shellscript` command, I receive the error _Failed to delete langauge-shellscript: Does not exist_ and the original Issue still appears even when I restart Atom (it does not appear to be re-installing the default `language-shellscript` package).
> 
> Should I just re-download the specific files that go in that **Release** folder (and if so, where can I get them?). And if I do, should I add the `'scopeName': 'text.tree-sitter'` line to the `tree-sitter-bash.cson`, as suggested in the original answer? Or is there a way to force Atom to install the `language-shellscript` package?

I am having the exact same issue as of today. Virus detection on Atom startup, folder deleted, windows, etc. 

What is the correct course of action here?

**Comment by GuillemotF** [comment]
Same issue here, Windows Defender has detected `language-shellscript` as a `Trojan:Win32/Azden.A` and removed it.

Manually installing `language-shellscript` by running `apm install language-shellscript` removes the error on Atom startup but shows a deprecation warning.

**Comment by LeonadoRivaldo** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 ia32
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [language-shellscript](https://github.com/atom/language-shellscript) package 0.27.9


### Stack Trace

Failed to load a language-shellscript package grammar

```
At Não foi possível encontrar o módulo especificado.
\\?\C:\Users\Leonardo Rivaldo\AppData\Local\atom\app-1.32.2\resources\app.asar.unpacked\node_modules\tree-sitter-bash\build\Release\tree_sitter_bash_binding.node in C:\Users\Leonardo Rivaldo\AppData\Local\atom\app-1.32.2\resources\app.asar\node_modules\language-shellscript\grammars\tree-sitter-bash.json

Error: Não foi possível encontrar o módulo especificado.
\\?\C:\Users\Leonardo Rivaldo\AppData\Local\atom\app-1.32.2\resources\app.asar.unpacked\node_modules\tree-sitter-bash\build\Release\tree_sitter_bash_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /app.asar/node_modules/tree-sitter-bash/index.js:1:173)
    at /app.asar/node_modules/tree-sitter-bash/index.js:3:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:1:623185)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:2955849)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:357769)
    at l.readFile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:357610)
    at u (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:576950)
    at ~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:578203
    at ELECTRON_ASAR.js:530:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
  at /app.asar/node_modules/language-shellscript/grammars/tree-sitter-bash.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angularjs 0.5.3 
angularjs-helper 0.10.2 
angularjs-snippets 0.10.18 
atom-clock 0.1.16 
atom-ide-ui 0.13.0 
atom-monokai 0.10.9 
atom-sublime-monokai-syntax 0.4.4 
atom-typescript 12.7.1 
autocomplete-html-entities 0.2.0 
autocomplete-javascript 0.0.2 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.26 
git-control 0.9.0 
git-status 0.3.4 
html-to-css 0.2.2 
ide-typescript 0.7.9 
indent-guide-improved 1.4.13 
javascript-snippets 1.2.1 
minimap 4.29.9 
remote-ftp 2.2.2 
tree-view-git-status 1.5.2 
underline-trailing-whitespace 1.4.2 
```

**Comment by whittede** [comment]
Manually re-installing using the steps @GuillemotF suggested results in the warning going away, but as soon as I open Atom my antivirus immediately flags the `tree_sitter_bash_binding.node` file as a Trojan again.

![image](https://user-images.githubusercontent.com/35239088/48962823-d1b14f00-ef3a-11e8-8123-649eacf856ea.png)

What steps should I proceed with here to have this default package file _not_ be detected as a virus?

**Comment by ChrisRay** [comment]
I am still getting this error has well.  I've followed the suggestions above but nothing worked.  I can't stop Panda antivirus from deleting the tree-sitter-bash.json as soon as I open Atom.  Should this issue be reopened if people are still having this problem?

**Comment by orcaaccounting** [comment]
> For anyone running across this.... you cannot uninstall from the GUI. You'll have to uninstall using `apm uninstall langauge-shellscript` and then restart atom.
Failed to delete language-shellscript: Does not exist

**Comment by fpunktz** [comment]
Me too. Were you able to fix it somehow?

**Comment by rsese** [comment]
If you don't have language-shellscript installed as a community package as originally reported (in which case the fix is to uninstall it) and  the issue is instead related to your antivirus program flagging particular files, there's nothing we can do on our end unfortunately.  The best thing to do is report as a false positive to your antivirus provider and you can share a direct link to the files since the project is open source.

**Comment by Preisschild** [comment]
I'm using Fedora Linux and have that issue. I installed it from this fedora copr: https://copr.fedorainfracloud.org/coprs/mosquito/atom/ 
Error Message: 
`Cannot find module './build/Release/tree_sitter_bash_binding' in /usr/lib64/atom/node_modules/language-shellscript/grammars/tree-sitter-bash.json`

Stacktrace:

```
Error: Cannot find module './build/Release/tree_sitter_bash_binding'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/usr/lib64/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib64/atom/src/module-cache.js:283:28)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/usr/lib64/atom/node_modules/language-shellscript/node_modules/tree-sitter-bash/index.js:1:173)
    at Object.<anonymous> (/usr/lib64/atom/node_modules/language-shellscript/node_modules/tree-sitter-bash/index.js:3:3)
    at Module._compile (/usr/lib64/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib64/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:47:27)
    at new TreeSitterGrammar (/usr/lib64/atom/src/tree-sitter-grammar.js:53:27)
    at GrammarRegistry.createGrammar (/usr/lib64/atom/src/grammar-registry.js:533:14)
    at CSON.readFile (/usr/lib64/atom/src/grammar-registry.js:515:29)
    at parseContents (/usr/lib64/atom/node_modules/season/lib/cson.js:119:7)
    at /usr/lib64/atom/node_modules/season/lib/cson.js:226:20
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
  at /usr/lib64/atom/node_modules/language-shellscript/grammars/tree-sitter-bash.json:1:1

```

**Comment by Arcanemagus** [comment]
@Preisschild that is an unsupported version of Atom.

Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
