### ISSUE TITLE
Wrong syntax coloring in shell scripts

### ISSUE THREAD

**Issue by yurivict** [atom/language-shellscript#97]
Please observe how two items ">&2 ;" are colored red, instead of just the first one: https://github.com/yurivict/freebsd-stats/blob/master/port-committer-productivity Semicolon is a command separator, and shouldn't be colored with ">&2".

Additionally, please consider differentiating the colors of ">"  and "&2", since they are, again, different elements, but the  coloring makes them look like they are one.

----

https://github.com/github/linguist selects language-shellscript for shell scripts in GitHub.

**Comment by 50Wliu** [comment]
This is an issue actually with GitHub's choice of how they decided to highlight `>&2 ;`.  `>&2` has different scopes (`keyword.operator.redirect.shell`) from `;` (`keyword.operator.list.shell`).  GitHub just chose to highlight them the same color.

As for your second issue about differentiating the scopes of `>&2`, please open a new issue.  Thanks!
