### ISSUE TITLE
shell script wrong syntax color 

### ISSUE THREAD

**Issue by aeschli** [atom/language-shellscript#99]
_From @eromoe on January 12, 2018 7:54_

- VSCode Version: 1.19.1
- OS Version: win7

This is fine:
![image](https://user-images.githubusercontent.com/3938751/34864832-0f7683fa-f7b1-11e7-9fad-38607d300557.png)

But : 

![image](https://user-images.githubusercontent.com/3938751/34864816-0919c30a-f7b1-11e7-8df0-41f197b4bf49.png)

You see? The last `{` .

test code : 
```bash
function setup_dircolors(){
    echo "####################################"
    echo "set dircolors"

    if [ ! -d ~/.dir_colors ]; then
        git clone https://github.com/seebi/dircolors-solarized ~/.dir_colors
    fi

    dircolorsdb=\$HOME/.dir_colors/dircolors.256dark

    if grep -q 'dircolors' ~/.zshrc ; then
        sed -i "s%dircolors .*%dircolors $dircolorsdb"`"%" ~/.zshrc
    else
        echo 'eval `dircolors '"$dircolorsdb"'`' >> ~/.zshrc
    fi
}
```

_Copied from original issue: Microsoft/vscode#41517_

**Comment by 50Wliu** [comment]
There are an odd number of backticks in the example given; I fail to see why this is a problem with language-shellscript and not the script itself.

**Comment by aeschli** [comment]
@eromoe More information is needed.

**Comment by eromoe** [comment]
@aeschli  50Wliu is right,  it is my fault.

**Comment by aeschli** [comment]
Ok, closing the issue then
